version: '3.7'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: TableStore
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8081:8080"
    restart: unless-stopped
#docker-compose up --build -d