
insert into categories (name) values ('Bàn Gaming E-DRA');
insert into categories (name) values ('Ghế gaming');
insert into categories (name) values ('Bàn chữ K');
insert into categories (name) values ('Ghế công thái học');
insert into categories (name) values ('Bàn công thái học');

insert into providers (name) values ('EDRA');
insert into providers (name) values ('Sihoo');
insert into providers (name) values ('Epion');
insert into providers (name) values ('Corsair');
insert into providers (name) values ('DXDracer');
insert into providers (name) values ('Razer');
insert into providers (name) values ('DErgo');

insert into products (name, color, price, in_stock, status, category_id, provider_id, img_path) values
                                                                                                    ("Bàn Gaming E-DRA EGT1610AR", "Đen", 2690000, 100, "Đang kinh doanh", 1, 1, "BanGamingE-DRAEGT1610AR.png"),
                                                                                                    ("Bàn Gaming E-DRA EGT1610AR-Grey", "Xám", 2690000, 100, "Đang kinh doanh", 1, 1, "BanGamingE-DRAEGT1610AR.png"),
                                                                                                    ("Ghế công thái học Sihoo M57-Black", "Đen", 3990000, 100, "Đang kinh doanh", 2, 2, "GhecongthaihocSihooM57.png"),
                                                                                                    ("Ghế công thái học Sihoo M57-Grey", "Xám", 3990000, 100, "Đang kinh doanh", 2, 2, "GhecongthaihocSihooM57.png"),
                                                                                                    ("Ghế AKRacing Core Series LX Plus - Pink", "Hồng", 5690000, 100, "Đang kinh doanh", 2, 5, "GheAKRacingCoreSeriesLXPlus.png");
insert into products (name, color, price, in_stock, status, category_id, provider_id, img_path) values ('Ghế Gaming Corsair TC100 RELAXED - Fabric (CF-9010052-WW) - Black','Black','4799000','50','Đang kinh doanh','2','1','6.webp');
insert into products (name, color, price, in_stock, status, category_id, provider_id, img_path) values ('Ghế Gaming Corsair TC100 RELAXED - Fabric (CF-9010052-WW) - Grey','Grey','4799000','30','Đang kinh doanh','2','2','6.webp');
insert into products (name, color, price, in_stock, status, category_id, provider_id, img_path) values ('Ghế Corsair TC200 Fabric Light Grey','Grey','8500000','10','Đang kinh doanh','2','4','tc200.webp');
insert into products (name, color, price, in_stock, status, category_id, provider_id, img_path) values ('Ghế Corsair TC200 Fabric Light White','White','8500000','30','Đang kinh doanh','2','4','tc2002.webp');
insert into products (name, color, price, in_stock, status, category_id, provider_id, img_path) values ('Ghế Corsair T3 Rush Gray-Charcoal','Grey','7100000','20','Đang kinh doanh','2','4','cst3rg.webp');
insert into products (name, color, price, in_stock, status, category_id, provider_id, img_path) values ('Ghế công thái học Epione Ergochair Pro 2.0','Black','9490000','25','Đang kinh doanh','4','3','ergo1.webp');
insert into products (name, color, price, in_stock, status, category_id, provider_id, img_path) values ('Ghế công thái học Epione EasyChair 2.0','Grey','7090000','15','Đang kinh doanh','4','3','eschair.webp');
insert into products (name, color, price, in_stock, status, category_id, provider_id, img_path) values ('Ghế công thái học Epione AliusChair','Black','13990000','20','Đang kinh doanh','4','3','aliuschair.webp');
insert into products (name, color, price, in_stock, status, category_id, provider_id, img_path) values ('Ghế DXRacer Drifting C NEO Leatherette Black&Red L (GC/LDC23LTA/NR)','Red','7490000','10','Đang kinh doanh','2','5','dxdrifting.jpeg');
insert into products (name, color, price, in_stock, status, category_id, provider_id, img_path) values ('Bàn chơi game DXRacer NEX TG-GDN001-NS-1','Black','3490000','20','Đang kinh doanh','2','5','dxdracerz.webp');
insert into products (name, color, price, in_stock, status, category_id, provider_id, img_path) values ('Bàn Làm Việc Đứng Điều Chỉnh Độ Cao Flexispot (Standard - 2 Stages) - EN1','Black','5950000','15','Đang kinh doanh','4','7','dergo1.webp');
insert into products (name, color, price, in_stock, status, category_id, provider_id, img_path) values ('Ghế gaming Razer Iskur NASA + AP (RZ38-02770300-R3U1)','Dark Gray','10990000','10','Đang kinh doanh','2','6','Razer1.webp');
insert into products (name, color, price, in_stock, status, category_id, provider_id, img_path) values ('Ghế gaming E-dra EGC229 level E','Black Red','2799000','20','Đang kinh doanh','2','1','EDRA2.webp');
insert into products (name, color, price, in_stock, status, category_id, provider_id, img_path) values ('Bàn công thái học ELT1675 Gaming Master','Black','4690000','10','Đang kinh doanh','5','1','elt1675l-thumb.png');
insert into products (name, color, price, in_stock, status, category_id, provider_id, img_path) values ('Bàn làm việc chân sắt chữ K mặt gỗ MDF BLV-02','Black','720000','10','Đang kinh doanh','3','1','279_z_5.jpg');
insert into products (name, color, price, in_stock, status, category_id, provider_id, img_path) values ('Bàn Chơi Game E-DRA Transformer','Red','1400000','10','Đang kinh doanh','1','1','279_z_1.jpg');
insert into products (name, color, price, in_stock, status, category_id, provider_id, img_path) values ('Bàn Chơi Game E-DRA EGT1675T - Eagle','Black','4100000','10','Đang kinh doanh','1','1','279_z_2.jpg');
insert into products (name, color, price, in_stock, status, category_id, provider_id, img_path) values ('Bàn chơi game E-DRA Z Tank - V3 - Pink','Pink','1099000','10','Đang kinh doanh','1','1','279_z_3.jpg');
insert into products (name, color, price, in_stock, status, category_id, provider_id, img_path) values ('Bàn chơi game E-DRA Z Tank - V3 - Red','Red','1099000','10','Đang kinh doanh','1','1','279_z_4.jpg');
INSERT INTO users(username, password, full_name, role, phone, email, address) VALUES
('AetherGS', 'paimon', 'Aether Tervat', 'customer', '0917862112', 'AetherGS@gmail.com', '1 Starfell Valley, Mondstadt, Tervat'),
('lengohau','$2a$10$UndjvYOSrlNG1XkJC1fP4OpEXigvJmFfXuoTNs4qqcT0TEH/knacS','Lê Ngô Hậu','ADMIN','09876543212','hau@gmail.com','TP. Hồ Chí Minh'),
('daisgu014','$2a$10$UndjvYOSrlNG1XkJC1fP4OpEXigvJmFfXuoTNs4qqcT0TEH/knacS','Nuyễn Hữu Đại','ADMIN','09876543222','dai@gmail.com','Bình Định'),
('daisgu013','$2a$10$UndjvYOSrlNG1XkJC1fP4OpEXigvJmFfXuoTNs4qqcT0TEH/knacS','Nuyễn Hữu Đại','USER','09876542122','dai@gmail.com','Bình Định');


insert into orders (total_price, create_at, user_id, place) values (10670000, '2023-8-7', 1, 'null'),
                                                                    (11070000, '2023-9-5', 1, 'null'),
                                                                    (3990000, '2023-11-8', 1, 'null');

insert into orders (total_price, create_at, user_id, place) values ('12677000','2023-11-1','4','null');
insert into orders (total_price, create_at, user_id, place) values ('79634000','2023-11-1','4','null');
insert into orders (total_price, create_at, user_id, place) values ('49798000','2023-11-1','1','null');
insert into orders (total_price, create_at, user_id, place) values ('39909000','2023-11-1','1','null');
insert into orders (total_price, create_at, user_id, place) values ('74529000','2023-11-1','1','null');
insert into orders (total_price, create_at, user_id, place) values ('117880000','2023-11-1','4','null');
insert into orders (total_price, create_at, user_id, place) values ('33827000','2023-11-1','4','null');
insert into orders (total_price, create_at, user_id, place) values ('79888000','2023-11-1','4','null');
insert into orders (total_price, create_at, user_id, place) values ('26040000','2023-11-1','4','null');
insert into orders (total_price, create_at, user_id, place) values ('58949000','2023-11-1','4','null');
insert into orders (total_price, create_at, user_id, place) values ('74840000','2023-11-2','1','null');
insert into orders (total_price, create_at, user_id, place) values ('59017000','2023-11-2','4','null');
insert into orders (total_price, create_at, user_id, place) values ('60168000','2023-11-2','4','null');
insert into orders (total_price, create_at, user_id, place) values ('88658000','2023-11-2','4','null');
insert into orders (total_price, create_at, user_id, place) values ('3899000','2023-11-2','4','null');
insert into orders (total_price, create_at, user_id, place) values ('21988000','2023-11-2','1','null');
insert into orders (total_price, create_at, user_id, place) values ('45180000','2023-11-2','1','null');
insert into orders (total_price, create_at, user_id, place) values ('8289000','2023-11-2','4','null');
insert into orders (total_price, create_at, user_id, place) values ('27170000','2023-11-3','1','null');
insert into orders (total_price, create_at, user_id, place) values ('20078000','2023-11-3','4','null');
insert into orders (total_price, create_at, user_id, place) values ('47844000','2023-11-3','4','null');
insert into orders (total_price, create_at, user_id, place) values ('56461000','2023-11-3','4','null');
insert into orders (total_price, create_at, user_id, place) values ('60915000','2023-11-3','1','null');
insert into orders (total_price, create_at, user_id, place) values ('54237000','2023-11-3','1','null');
insert into orders (total_price, create_at, user_id, place) values ('24943000','2023-11-3','4','null');
insert into orders (total_price, create_at, user_id, place) values ('83647000','2023-11-3','4','null');
insert into orders (total_price, create_at, user_id, place) values ('31767000','2023-11-4','1','null');
insert into orders (total_price, create_at, user_id, place) values ('76530000','2023-11-4','1','null');
insert into orders (total_price, create_at, user_id, place) values ('2160000','2023-11-4','1','null');
insert into orders (total_price, create_at, user_id, place) values ('26600000','2023-11-4','1','null');
insert into orders (total_price, create_at, user_id, place) values ('44440000','2023-11-4','1','null');
insert into orders (total_price, create_at, user_id, place) values ('40560000','2023-11-4','4','null');
insert into orders (total_price, create_at, user_id, place) values ('71347000','2023-11-4','1','null');
insert into orders (total_price, create_at, user_id, place) values ('35336000','2023-11-4','1','null');
insert into orders (total_price, create_at, user_id, place) values ('49565000','2023-11-5','1','null');
insert into orders (total_price, create_at, user_id, place) values ('26088000','2023-11-5','4','null');
insert into orders (total_price, create_at, user_id, place) values ('22858000','2023-11-5','1','null');
insert into orders (total_price, create_at, user_id, place) values ('40617000','2023-11-5','4','null');
insert into orders (total_price, create_at, user_id, place) values ('20479000','2023-11-5','4','null');
insert into orders (total_price, create_at, user_id, place) values ('84777000','2023-11-5','1','null');
insert into orders (total_price, create_at, user_id, place) values ('57067000','2023-11-5','1','null');
insert into orders (total_price, create_at, user_id, place) values ('23640000','2023-11-5','1','null');
insert into orders (total_price, create_at, user_id, place) values ('30884000','2023-11-6','1','null');
insert into orders (total_price, create_at, user_id, place) values ('90787000','2023-11-6','1','null');
insert into orders (total_price, create_at, user_id, place) values ('86140000','2023-11-6','1','null');
insert into orders (total_price, create_at, user_id, place) values ('34289000','2023-11-6','4','null');
insert into orders (total_price, create_at, user_id, place) values ('40568000','2023-11-7','4','null');
insert into orders (total_price, create_at, user_id, place) values ('82759000','2023-11-7','4','null');
insert into orders (total_price, create_at, user_id, place) values ('28060000','2023-11-7','4','null');
insert into orders (total_price, create_at, user_id, place) values ('40254000','2023-11-7','4','null');
insert into orders (total_price, create_at, user_id, place) values ('36060000','2023-11-7','4','null');
insert into orders (total_price, create_at, user_id, place) values ('68863000','2023-11-7','1','null');
insert into orders (total_price, create_at, user_id, place) values ('18388000','2023-11-8','1','null');
insert into orders (total_price, create_at, user_id, place) values ('23075000','2023-11-8','1','null');
insert into orders (total_price, create_at, user_id, place) values ('42757000','2023-11-8','1','null');
insert into orders (total_price, create_at, user_id, place) values ('13989000','2023-11-8','4','null');
insert into orders (total_price, create_at, user_id, place) values ('28910000','2023-11-8','4','null');

insert into orderDetails (order_id, product_id, qty) values (1, 0000000001, 1),
                                                           (1, 0000000003, 2),
                                                           (2, 0000000002, 1),
                                                           (2, 0000000001, 1),
                                                           (2, 0000000005, 1),
                                                           (3, 0000000004, 1);

insert into orderDetails (order_id, product_id, qty) values ('4','19','2');
insert into orderDetails (order_id, product_id, qty) values ('4','23','3');
insert into orderDetails (order_id, product_id, qty) values ('5','6','2');
insert into orderDetails (order_id, product_id, qty) values ('5','7','2');
insert into orderDetails (order_id, product_id, qty) values ('5','8','2');
insert into orderDetails (order_id, product_id, qty) values ('5','12','1');
insert into orderDetails (order_id, product_id, qty) values ('5','15','3');
insert into orderDetails (order_id, product_id, qty) values ('5','17','2');
insert into orderDetails (order_id, product_id, qty) values ('5','18','1');
insert into orderDetails (order_id, product_id, qty) values ('5','23','1');
insert into orderDetails (order_id, product_id, qty) values ('6','9','2');
insert into orderDetails (order_id, product_id, qty) values ('6','11','1');
insert into orderDetails (order_id, product_id, qty) values ('6','14','2');
insert into orderDetails (order_id, product_id, qty) values ('6','19','1');
insert into orderDetails (order_id, product_id, qty) values ('6','20','2');
insert into orderDetails (order_id, product_id, qty) values ('6','23','2');
insert into orderDetails (order_id, product_id, qty) values ('7','12','2');
insert into orderDetails (order_id, product_id, qty) values ('7','14','3');
insert into orderDetails (order_id, product_id, qty) values ('7','20','3');
insert into orderDetails (order_id, product_id, qty) values ('7','23','1');
insert into orderDetails (order_id, product_id, qty) values ('8','7','1');
insert into orderDetails (order_id, product_id, qty) values ('8','11','2');
insert into orderDetails (order_id, product_id, qty) values ('8','16','2');
insert into orderDetails (order_id, product_id, qty) values ('8','17','2');
insert into orderDetails (order_id, product_id, qty) values ('8','19','3');
insert into orderDetails (order_id, product_id, qty) values ('8','21','2');
insert into orderDetails (order_id, product_id, qty) values ('9','8','1');
insert into orderDetails (order_id, product_id, qty) values ('9','11','2');
insert into orderDetails (order_id, product_id, qty) values ('9','12','3');
insert into orderDetails (order_id, product_id, qty) values ('9','13','3');
insert into orderDetails (order_id, product_id, qty) values ('9','15','1');
insert into orderDetails (order_id, product_id, qty) values ('9','19','3');
insert into orderDetails (order_id, product_id, qty) values ('9','21','1');
insert into orderDetails (order_id, product_id, qty) values ('9','22','2');
insert into orderDetails (order_id, product_id, qty) values ('10','6','2');
insert into orderDetails (order_id, product_id, qty) values ('10','10','2');
insert into orderDetails (order_id, product_id, qty) values ('10','14','1');
insert into orderDetails (order_id, product_id, qty) values ('10','20','2');
insert into orderDetails (order_id, product_id, qty) values ('10','24','1');
insert into orderDetails (order_id, product_id, qty) values ('11','11','3');
insert into orderDetails (order_id, product_id, qty) values ('11','12','2');
insert into orderDetails (order_id, product_id, qty) values ('11','13','1');
insert into orderDetails (order_id, product_id, qty) values ('11','15','2');
insert into orderDetails (order_id, product_id, qty) values ('11','19','3');
insert into orderDetails (order_id, product_id, qty) values ('11','23','2');
insert into orderDetails (order_id, product_id, qty) values ('12','8','1');
insert into orderDetails (order_id, product_id, qty) values ('12','14','1');
insert into orderDetails (order_id, product_id, qty) values ('12','16','1');
insert into orderDetails (order_id, product_id, qty) values ('12','22','1');
insert into orderDetails (order_id, product_id, qty) values ('13','7','1');
insert into orderDetails (order_id, product_id, qty) values ('13','13','3');
insert into orderDetails (order_id, product_id, qty) values ('13','14','1');
insert into orderDetails (order_id, product_id, qty) values ('13','19','1');
insert into orderDetails (order_id, product_id, qty) values ('14','11','1');
insert into orderDetails (order_id, product_id, qty) values ('14','13','3');
insert into orderDetails (order_id, product_id, qty) values ('14','17','2');
insert into orderDetails (order_id, product_id, qty) values ('14','21','1');
insert into orderDetails (order_id, product_id, qty) values ('15','7','3');
insert into orderDetails (order_id, product_id, qty) values ('15','11','3');
insert into orderDetails (order_id, product_id, qty) values ('15','13','1');
insert into orderDetails (order_id, product_id, qty) values ('15','20','3');
insert into orderDetails (order_id, product_id, qty) values ('16','7','1');
insert into orderDetails (order_id, product_id, qty) values ('16','13','3');
insert into orderDetails (order_id, product_id, qty) values ('16','22','3');
insert into orderDetails (order_id, product_id, qty) values ('16','23','1');
insert into orderDetails (order_id, product_id, qty) values ('17','9','3');
insert into orderDetails (order_id, product_id, qty) values ('17','10','3');
insert into orderDetails (order_id, product_id, qty) values ('17','13','1');
insert into orderDetails (order_id, product_id, qty) values ('17','18','2');
insert into orderDetails (order_id, product_id, qty) values ('17','19','3');
insert into orderDetails (order_id, product_id, qty) values ('17','22','2');
insert into orderDetails (order_id, product_id, qty) values ('18','21','2');
insert into orderDetails (order_id, product_id, qty) values ('18','24','1');
insert into orderDetails (order_id, product_id, qty) values ('19','14','1');
insert into orderDetails (order_id, product_id, qty) values ('19','22','3');
insert into orderDetails (order_id, product_id, qty) values ('19','23','2');
insert into orderDetails (order_id, product_id, qty) values ('20','12','3');
insert into orderDetails (order_id, product_id, qty) values ('20','14','3');
insert into orderDetails (order_id, product_id, qty) values ('20','20','2');
insert into orderDetails (order_id, product_id, qty) values ('21','6','1');
insert into orderDetails (order_id, product_id, qty) values ('21','15','1');
insert into orderDetails (order_id, product_id, qty) values ('22','9','1');
insert into orderDetails (order_id, product_id, qty) values ('22','15','3');
insert into orderDetails (order_id, product_id, qty) values ('22','22','2');
insert into orderDetails (order_id, product_id, qty) values ('23','7','1');
insert into orderDetails (order_id, product_id, qty) values ('23','12','2');
insert into orderDetails (order_id, product_id, qty) values ('23','23','1');
insert into orderDetails (order_id, product_id, qty) values ('24','6','3');
insert into orderDetails (order_id, product_id, qty) values ('24','8','2');
insert into orderDetails (order_id, product_id, qty) values ('24','17','1');
insert into orderDetails (order_id, product_id, qty) values ('24','20','3');
insert into orderDetails (order_id, product_id, qty) values ('24','23','3');
insert into orderDetails (order_id, product_id, qty) values ('25','7','3');
insert into orderDetails (order_id, product_id, qty) values ('25','13','2');
insert into orderDetails (order_id, product_id, qty) values ('25','14','1');
insert into orderDetails (order_id, product_id, qty) values ('25','23','3');
insert into orderDetails (order_id, product_id, qty) values ('25','24','3');
insert into orderDetails (order_id, product_id, qty) values ('26','6','2');
insert into orderDetails (order_id, product_id, qty) values ('26','9','1');
insert into orderDetails (order_id, product_id, qty) values ('26','12','3');
insert into orderDetails (order_id, product_id, qty) values ('26','16','1');
insert into orderDetails (order_id, product_id, qty) values ('26','22','3');
insert into orderDetails (order_id, product_id, qty) values ('26','23','3');
insert into orderDetails (order_id, product_id, qty) values ('27','7','1');
insert into orderDetails (order_id, product_id, qty) values ('27','8','1');
insert into orderDetails (order_id, product_id, qty) values ('27','10','2');
insert into orderDetails (order_id, product_id, qty) values ('27','15','3');
insert into orderDetails (order_id, product_id, qty) values ('27','19','3');
insert into orderDetails (order_id, product_id, qty) values ('27','24','2');
insert into orderDetails (order_id, product_id, qty) values ('28','7','2');
insert into orderDetails (order_id, product_id, qty) values ('28','15','1');
insert into orderDetails (order_id, product_id, qty) values ('28','20','3');
insert into orderDetails (order_id, product_id, qty) values ('28','21','3');
insert into orderDetails (order_id, product_id, qty) values ('28','23','3');
insert into orderDetails (order_id, product_id, qty) values ('28','24','2');
insert into orderDetails (order_id, product_id, qty) values ('29','7','3');
insert into orderDetails (order_id, product_id, qty) values ('29','10','3');
insert into orderDetails (order_id, product_id, qty) values ('29','14','1');
insert into orderDetails (order_id, product_id, qty) values ('29','17','3');
insert into orderDetails (order_id, product_id, qty) values ('29','19','1');
insert into orderDetails (order_id, product_id, qty) values ('29','21','2');
insert into orderDetails (order_id, product_id, qty) values ('30','11','3');
insert into orderDetails (order_id, product_id, qty) values ('30','23','1');
insert into orderDetails (order_id, product_id, qty) values ('30','24','2');
insert into orderDetails (order_id, product_id, qty) values ('31','8','3');
insert into orderDetails (order_id, product_id, qty) values ('31','12','3');
insert into orderDetails (order_id, product_id, qty) values ('31','14','1');
insert into orderDetails (order_id, product_id, qty) values ('31','19','3');
insert into orderDetails (order_id, product_id, qty) values ('31','22','2');
insert into orderDetails (order_id, product_id, qty) values ('32','20','3');
insert into orderDetails (order_id, product_id, qty) values ('33','9','2');
insert into orderDetails (order_id, product_id, qty) values ('33','21','1');
insert into orderDetails (order_id, product_id, qty) values ('33','22','2');
insert into orderDetails (order_id, product_id, qty) values ('34','13','1');
insert into orderDetails (order_id, product_id, qty) values ('34','14','2');
insert into orderDetails (order_id, product_id, qty) values ('34','19','3');
insert into orderDetails (order_id, product_id, qty) values ('34','21','1');
insert into orderDetails (order_id, product_id, qty) values ('35','9','2');
insert into orderDetails (order_id, product_id, qty) values ('35','11','1');
insert into orderDetails (order_id, product_id, qty) values ('35','19','3');
insert into orderDetails (order_id, product_id, qty) values ('36','8','3');
insert into orderDetails (order_id, product_id, qty) values ('36','13','2');
insert into orderDetails (order_id, product_id, qty) values ('36','15','3');
insert into orderDetails (order_id, product_id, qty) values ('36','22','1');
insert into orderDetails (order_id, product_id, qty) values ('36','23','3');
insert into orderDetails (order_id, product_id, qty) values ('37','6','2');
insert into orderDetails (order_id, product_id, qty) values ('37','11','1');
insert into orderDetails (order_id, product_id, qty) values ('37','12','1');
insert into orderDetails (order_id, product_id, qty) values ('37','18','2');
insert into orderDetails (order_id, product_id, qty) values ('37','20','3');
insert into orderDetails (order_id, product_id, qty) values ('37','21','1');
insert into orderDetails (order_id, product_id, qty) values ('38','6','3');
insert into orderDetails (order_id, product_id, qty) values ('38','17','3');
insert into orderDetails (order_id, product_id, qty) values ('38','24','2');
insert into orderDetails (order_id, product_id, qty) values ('39','6','2');
insert into orderDetails (order_id, product_id, qty) values ('39','17','1');
insert into orderDetails (order_id, product_id, qty) values ('39','21','1');
insert into orderDetails (order_id, product_id, qty) values ('39','22','1');
insert into orderDetails (order_id, product_id, qty) values ('40','13','1');
insert into orderDetails (order_id, product_id, qty) values ('40','16','1');
insert into orderDetails (order_id, product_id, qty) values ('40','20','1');
insert into orderDetails (order_id, product_id, qty) values ('40','23','2');
insert into orderDetails (order_id, product_id, qty) values ('41','7','3');
insert into orderDetails (order_id, product_id, qty) values ('41','8','3');
insert into orderDetails (order_id, product_id, qty) values ('41','20','1');
insert into orderDetails (order_id, product_id, qty) values ('42','6','1');
insert into orderDetails (order_id, product_id, qty) values ('42','17','1');
insert into orderDetails (order_id, product_id, qty) values ('42','19','1');
insert into orderDetails (order_id, product_id, qty) values ('43','6','3');
insert into orderDetails (order_id, product_id, qty) values ('43','8','2');
insert into orderDetails (order_id, product_id, qty) values ('43','9','2');
insert into orderDetails (order_id, product_id, qty) values ('43','11','2');
insert into orderDetails (order_id, product_id, qty) values ('43','16','2');
insert into orderDetails (order_id, product_id, qty) values ('43','21','1');
insert into orderDetails (order_id, product_id, qty) values ('43','22','1');
insert into orderDetails (order_id, product_id, qty) values ('44','6','3');
insert into orderDetails (order_id, product_id, qty) values ('44','10','2');
insert into orderDetails (order_id, product_id, qty) values ('44','11','3');
insert into orderDetails (order_id, product_id, qty) values ('45','11','1');
insert into orderDetails (order_id, product_id, qty) values ('45','16','1');
insert into orderDetails (order_id, product_id, qty) values ('45','22','2');
insert into orderDetails (order_id, product_id, qty) values ('46','6','1');
insert into orderDetails (order_id, product_id, qty) values ('46','7','3');
insert into orderDetails (order_id, product_id, qty) values ('46','11','1');
insert into orderDetails (order_id, product_id, qty) values ('46','24','2');
insert into orderDetails (order_id, product_id, qty) values ('47','9','3');
insert into orderDetails (order_id, product_id, qty) values ('47','12','1');
insert into orderDetails (order_id, product_id, qty) values ('47','13','3');
insert into orderDetails (order_id, product_id, qty) values ('47','15','2');
insert into orderDetails (order_id, product_id, qty) values ('47','16','1');
insert into orderDetails (order_id, product_id, qty) values ('47','23','3');
insert into orderDetails (order_id, product_id, qty) values ('48','9','3');
insert into orderDetails (order_id, product_id, qty) values ('48','13','3');
insert into orderDetails (order_id, product_id, qty) values ('48','15','3');
insert into orderDetails (order_id, product_id, qty) values ('48','22','2');
insert into orderDetails (order_id, product_id, qty) values ('49','13','1');
insert into orderDetails (order_id, product_id, qty) values ('49','14','1');
insert into orderDetails (order_id, product_id, qty) values ('49','17','1');
insert into orderDetails (order_id, product_id, qty) values ('49','20','1');
insert into orderDetails (order_id, product_id, qty) values ('49','24','1');
insert into orderDetails (order_id, product_id, qty) values ('50','7','2');
insert into orderDetails (order_id, product_id, qty) values ('50','8','1');
insert into orderDetails (order_id, product_id, qty) values ('50','14','3');
insert into orderDetails (order_id, product_id, qty) values ('51','7','1');
insert into orderDetails (order_id, product_id, qty) values ('51','9','3');
insert into orderDetails (order_id, product_id, qty) values ('51','13','1');
insert into orderDetails (order_id, product_id, qty) values ('51','14','3');
insert into orderDetails (order_id, product_id, qty) values ('51','16','2');
insert into orderDetails (order_id, product_id, qty) values ('51','22','1');
insert into orderDetails (order_id, product_id, qty) values ('52','13','1');
insert into orderDetails (order_id, product_id, qty) values ('52','19','3');
insert into orderDetails (order_id, product_id, qty) values ('53','11','1');
insert into orderDetails (order_id, product_id, qty) values ('53','14','3');
insert into orderDetails (order_id, product_id, qty) values ('53','18','1');
insert into orderDetails (order_id, product_id, qty) values ('53','23','2');
insert into orderDetails (order_id, product_id, qty) values ('53','24','3');
insert into orderDetails (order_id, product_id, qty) values ('54','12','3');
insert into orderDetails (order_id, product_id, qty) values ('54','19','3');
insert into orderDetails (order_id, product_id, qty) values ('54','20','1');
insert into orderDetails (order_id, product_id, qty) values ('55','6','1');
insert into orderDetails (order_id, product_id, qty) values ('55','7','3');
insert into orderDetails (order_id, product_id, qty) values ('55','10','3');
insert into orderDetails (order_id, product_id, qty) values ('55','11','2');
insert into orderDetails (order_id, product_id, qty) values ('55','19','1');
insert into orderDetails (order_id, product_id, qty) values ('55','21','1');
insert into orderDetails (order_id, product_id, qty) values ('55','23','3');
insert into orderDetails (order_id, product_id, qty) values ('56','7','2');
insert into orderDetails (order_id, product_id, qty) values ('56','19','1');
insert into orderDetails (order_id, product_id, qty) values ('56','22','1');
insert into orderDetails (order_id, product_id, qty) values ('57','12','2');
insert into orderDetails (order_id, product_id, qty) values ('57','18','2');
insert into orderDetails (order_id, product_id, qty) values ('57','24','3');
insert into orderDetails (order_id, product_id, qty) values ('58','7','3');
insert into orderDetails (order_id, product_id, qty) values ('58','13','1');
insert into orderDetails (order_id, product_id, qty) values ('58','15','2');
insert into orderDetails (order_id, product_id, qty) values ('58','16','1');
insert into orderDetails (order_id, product_id, qty) values ('58','20','2');
insert into orderDetails (order_id, product_id, qty) values ('59','19','1');
insert into orderDetails (order_id, product_id, qty) values ('59','22','2');
insert into orderDetails (order_id, product_id, qty) values ('59','24','1');
insert into orderDetails (order_id, product_id, qty) values ('60','8','2');
insert into orderDetails (order_id, product_id, qty) values ('60','15','3');
insert into orderDetails (order_id, product_id, qty) values ('60','20','2');